language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer install --no-interaction --prefer-source --dev
  - phpenv rehash
script:
  - cd tests
  - XDEBUG_MODE=coverage ../vendor/bin/phpunit --coverage-text .
  - cd ..
  - ./vendor/bin/phpcs --standard=PEAR src/
